services:
  controller-server:
    build: .
    container_name: cheaptroller-controller-server
    privileged: true                  
    devices:
      - "/dev/uinput:/dev/uinput"
    network_mode: "host"
    restart: unless-stopped
